/**
 * Reads the first-party plugin source trees (examples/plugins/*) and emits a
 * generated TypeScript module that embeds them as SIGNED PluginPackage
 * literals. The UI's syncPlugins auto-install path imports this module — no
 * network fetch, no zip — the plugin source ships inside the UI bundle.
 *
 * Signing (see bundleSigning.ts): with OPENBOOK_REGISTRY_PRIVATE_KEY set
 * (release CI), packages are signed by the production registry key so fresh
 * installs verify against the pinned OPENBOOK_REGISTRY public key; otherwise
 * the committed TEST-ONLY key signs them (trusted nowhere by default — e2e
 * trusts it explicitly). Ed25519 is deterministic, so the git-tracked output
 * is byte-stable across regenerations with the same key.
 *
 * Run: `npx tsx scripts/bundlePlugins.ts`
 * Output: `src/plugins/bundled.gen.ts` (git-tracked, regenerated on build)
 */

import {readFileSync, readdirSync, writeFileSync, statSync} from 'fs';
import {join, relative, resolve} from 'path';
import {OPENBOOK_REGISTRY_KEYS} from '@book.dev/sdk';
import {resolveSigningKey, signBundledPackage} from './bundleSigning';

const ROOT = resolve(import.meta.dirname, '..', '..', '..');
const OUT = resolve(import.meta.dirname, '..', 'src', 'plugins', 'bundled.gen.ts');
// Machine-readable sidecar of the emitted signatures, so release CI can
// assert the built bundle is signed by a pinned key without parsing/executing
// bundled.gen.ts (scripts/check-bundled-signatures.mjs).
const SIG_OUT = resolve(import.meta.dirname, '..', 'src', 'plugins', 'bundled.signatures.json');

/** Recursively collect all files under `dir`, returning paths relative to `base`. */
function walk(dir: string, base: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full, base));
    } else {
      results.push(relative(base, full));
    }
  }
  return results;
}

interface BundledPlugin {
  dir: string;
}

/** First-party plugins to bundle. Add entries here to ship more plugins. */
const PLUGINS: BundledPlugin[] = [
  {dir: 'examples/plugins/ledger'},
];

// The signing key: the OPENBOOK_REGISTRY_PRIVATE_KEY env var (production/CI
// release) or the committed TEST-ONLY key. Loud about which, so build logs
// always show the provenance the bundle will carry.
const signingKey = resolveSigningKey();
if (signingKey.source === 'test') {
  console.warn(
    '[bundlePlugins] OPENBOOK_REGISTRY_PRIVATE_KEY is unset — signing with the committed TEST-ONLY key ' +
      '(scripts/test-registry-key.json). Fine for dev/test; production builds must set the secret (docs/plugin-signing.md).',
  );
} else if (!OPENBOOK_REGISTRY_KEYS.some((k) => k.publicKey === signingKey.publicKey)) {
  console.warn(
    `[bundlePlugins] signing with an env key whose public half (${signingKey.publicKey}) matches NO pinned ` +
      'OPENBOOK_REGISTRY_KEYS entry — installs will show Unverified unless clients trust it. Expected during rotation ' +
      'overlap or local throwaway-key testing; wrong for a production release.',
  );
}

const emittedSignatures: Array<{id: string; registry: string; publicKey: string}> = [];

let out = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/bundlePlugins.ts — do not edit by hand.
 * Re-generate: \`pnpm run gen:bundled-plugins\`
 *
 * Signed by: ${signingKey.registry} (${signingKey.source === 'test' ? 'TEST-ONLY key — not trusted by default' : 'key from OPENBOOK_REGISTRY_PRIVATE_KEY'})
 */
import type {PluginPackage} from '@book.dev/sdk';

`;

for (const plugin of PLUGINS) {
  const pluginDir = resolve(ROOT, plugin.dir);
  const manifestPath = join(pluginDir, 'openbook.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  const id: string = manifest.id;

  // Collect source files (ts/tsx/js/jsx/json, excluding openbook.json itself)
  const allFiles = walk(pluginDir, pluginDir).filter(
    (f) => !f.startsWith('.') && !f.startsWith('__') && /\.(ts|tsx|js|jsx|json)$/.test(f),
  );

  const filesRecord: Record<string, string> = {};
  for (const f of allFiles.sort()) {
    if (f === 'openbook.json') continue; // manifest is separate
    filesRecord[f] = readFileSync(join(pluginDir, f), 'utf-8');
  }

  // Validate the entry file exists
  if (!(manifest.main in filesRecord)) {
    throw new Error(`entry file "${manifest.main}" not found in ${plugin.dir}`);
  }

  // Sign the exact package literal being emitted — registry provenance for
  // the auto-installed first-party plugins (verified per sync in host.ts).
  const signature = await signBundledPackage({manifest, files: filesRecord}, signingKey);
  emittedSignatures.push({id, registry: signature.registry, publicKey: signature.publicKey});

  const varName = id.replace(/[^a-zA-Z0-9]/g, '_');
  out += `export const ${varName}: PluginPackage = {\n`;
  out += `  manifest: ${JSON.stringify(manifest, null, 2).replace(/\n/g, '\n  ')},\n`;
  out += '  files: {\n';
  for (const [path, content] of Object.entries(filesRecord)) {
    // Use JSON.stringify for safe escaping of the source text
    out += `    ${JSON.stringify(path)}: ${JSON.stringify(content)},\n`;
  }
  out += '  },\n';
  out += `  signature: ${JSON.stringify(signature, null, 2).replace(/\n/g, '\n  ')},\n`;
  out += '};\n\n';
}

out += '/** Every first-party plugin the app ships with. */\n';
out += 'export const BUNDLED_PLUGINS: PluginPackage[] = [\n';
for (const plugin of PLUGINS) {
  const pluginDir = resolve(ROOT, plugin.dir);
  const manifest = JSON.parse(readFileSync(join(pluginDir, 'openbook.json'), 'utf-8'));
  const varName = (manifest.id as string).replace(/[^a-zA-Z0-9]/g, '_');
  out += `  ${varName},\n`;
}
out += '];\n';

writeFileSync(OUT, out);
writeFileSync(SIG_OUT, `${JSON.stringify(emittedSignatures, null, 2)}\n`);
console.log(
  `wrote ${relative(process.cwd(), OUT)} (${PLUGINS.length} plugin(s), signed by ${signingKey.registry} [${signingKey.source}])`,
);
