/**
 * Reads the first-party plugin source trees (examples/plugins/*) and emits a
 * generated TypeScript module that embeds them as PluginPackage literals. The
 * UI's syncPlugins auto-install path imports this module — no network fetch,
 * no zip — the plugin source ships inside the UI bundle.
 *
 * Run: `npx tsx scripts/bundlePlugins.ts`
 * Output: `src/plugins/bundled.gen.ts` (git-tracked, regenerated on build)
 */

import {readFileSync, readdirSync, writeFileSync, statSync} from 'fs';
import {join, relative, resolve} from 'path';

const ROOT = resolve(import.meta.dirname, '..', '..', '..');
const OUT = resolve(import.meta.dirname, '..', 'src', 'plugins', 'bundled.gen.ts');

/** Recursively collect all files under `dir`, returning paths relative to `base`. */
function walk(dir: string, base: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full, base));
    } else {
      results.push(relative(base, full));
    }
  }
  return results;
}

interface BundledPlugin {
  dir: string;
}

/** First-party plugins to bundle. Add entries here to ship more plugins. */
const PLUGINS: BundledPlugin[] = [
  {dir: 'examples/plugins/ledger'},
];

let out = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/bundlePlugins.ts — do not edit by hand.
 * Re-generate: \`pnpm run gen:bundled-plugins\`
 */
import type {PluginPackage} from '@book.dev/sdk';

`;

for (const plugin of PLUGINS) {
  const pluginDir = resolve(ROOT, plugin.dir);
  const manifestPath = join(pluginDir, 'openbook.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  const id: string = manifest.id;

  // Collect source files (ts/tsx/js/jsx/json, excluding openbook.json itself)
  const allFiles = walk(pluginDir, pluginDir).filter(
    (f) => !f.startsWith('.') && !f.startsWith('__') && /\.(ts|tsx|js|jsx|json)$/.test(f),
  );

  const filesRecord: Record<string, string> = {};
  for (const f of allFiles.sort()) {
    if (f === 'openbook.json') continue; // manifest is separate
    filesRecord[f] = readFileSync(join(pluginDir, f), 'utf-8');
  }

  // Validate the entry file exists
  if (!(manifest.main in filesRecord)) {
    throw new Error(`entry file "${manifest.main}" not found in ${plugin.dir}`);
  }

  const varName = id.replace(/[^a-zA-Z0-9]/g, '_');
  out += `export const ${varName}: PluginPackage = {\n`;
  out += `  manifest: ${JSON.stringify(manifest, null, 2).replace(/\n/g, '\n  ')},\n`;
  out += '  files: {\n';
  for (const [path, content] of Object.entries(filesRecord)) {
    // Use JSON.stringify for safe escaping of the source text
    out += `    ${JSON.stringify(path)}: ${JSON.stringify(content)},\n`;
  }
  out += '  },\n';
  out += '};\n\n';
}

out += '/** Every first-party plugin the app ships with. */\n';
out += 'export const BUNDLED_PLUGINS: PluginPackage[] = [\n';
for (const plugin of PLUGINS) {
  const pluginDir = resolve(ROOT, plugin.dir);
  const manifest = JSON.parse(readFileSync(join(pluginDir, 'openbook.json'), 'utf-8'));
  const varName = (manifest.id as string).replace(/[^a-zA-Z0-9]/g, '_');
  out += `  ${varName},\n`;
}
out += '];\n';

writeFileSync(OUT, out);
console.log(`wrote ${relative(process.cwd(), OUT)} (${PLUGINS.length} plugin(s))`);
