/**
 * Reads the first-party plugin source trees (examples/plugins/*) and emits a
 * generated TypeScript module that embeds them as PluginPackage literals. The
 * UI's syncPlugins auto-install path imports this module — no network fetch,
 * no zip — the plugin source ships inside the UI bundle.
 *
 * ALSO mirrors the ledger plugin's PURE report-fold modules (`reports.ts`,
 * `statements.ts` — no React, no IO, no host calls) into
 * `src/export/ledgerFolds.gen/` as compilable TypeScript, with the loader-only
 * `@book.dev/plugin-sdk` import rewritten to `@book.dev/sdk` (the host module
 * those money functions come from anyway). The static HTML export (LX-3)
 * imports the folds from there to render ledger REPORT blocks as real tables —
 * the plugin source stays the single source of truth, and the export bundle
 * never gains the plugin runtime (the mirrored modules are pure functions).
 *
 * Run: `npx tsx scripts/bundlePlugins.ts`
 * Output: `src/plugins/bundled.gen.ts` + `src/export/ledgerFolds.gen/*.ts`
 * (git-tracked, regenerated on build)
 */

import {mkdirSync, readFileSync, readdirSync, writeFileSync, statSync} from 'fs';
import {join, relative, resolve} from 'path';

const ROOT = resolve(import.meta.dirname, '..', '..', '..');
const OUT = resolve(import.meta.dirname, '..', 'src', 'plugins', 'bundled.gen.ts');
const FOLDS_OUT_DIR = resolve(import.meta.dirname, '..', 'src', 'export', 'ledgerFolds.gen');

/** The ledger plugin's pure fold modules the export renderer compiles in. */
const LEDGER_FOLD_MODULES = ['reports.ts', 'statements.ts'] as const;

/** Recursively collect all files under `dir`, returning paths relative to `base`. */
function walk(dir: string, base: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full, base));
    } else {
      results.push(relative(base, full));
    }
  }
  return results;
}

interface BundledPlugin {
  dir: string;
}

/** First-party plugins to bundle. Add entries here to ship more plugins. */
const PLUGINS: BundledPlugin[] = [
  {dir: 'examples/plugins/ledger'},
];

let out = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/bundlePlugins.ts — do not edit by hand.
 * Re-generate: \`pnpm run gen:bundled-plugins\`
 */
import type {PluginPackage} from '@book.dev/sdk';

`;

for (const plugin of PLUGINS) {
  const pluginDir = resolve(ROOT, plugin.dir);
  const manifestPath = join(pluginDir, 'openbook.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  const id: string = manifest.id;

  // Collect source files (ts/tsx/js/jsx/json, excluding openbook.json itself)
  const allFiles = walk(pluginDir, pluginDir).filter(
    (f) => !f.startsWith('.') && !f.startsWith('__') && /\.(ts|tsx|js|jsx|json)$/.test(f),
  );

  const filesRecord: Record<string, string> = {};
  for (const f of allFiles.sort()) {
    if (f === 'openbook.json') continue; // manifest is separate
    filesRecord[f] = readFileSync(join(pluginDir, f), 'utf-8');
  }

  // Validate the entry file exists
  if (!(manifest.main in filesRecord)) {
    throw new Error(`entry file "${manifest.main}" not found in ${plugin.dir}`);
  }

  const varName = id.replace(/[^a-zA-Z0-9]/g, '_');
  out += `export const ${varName}: PluginPackage = {\n`;
  out += `  manifest: ${JSON.stringify(manifest, null, 2).replace(/\n/g, '\n  ')},\n`;
  out += '  files: {\n';
  for (const [path, content] of Object.entries(filesRecord)) {
    // Use JSON.stringify for safe escaping of the source text
    out += `    ${JSON.stringify(path)}: ${JSON.stringify(content)},\n`;
  }
  out += '  },\n';
  out += '};\n\n';
}

out += '/** Every first-party plugin the app ships with. */\n';
out += 'export const BUNDLED_PLUGINS: PluginPackage[] = [\n';
for (const plugin of PLUGINS) {
  const pluginDir = resolve(ROOT, plugin.dir);
  const manifest = JSON.parse(readFileSync(join(pluginDir, 'openbook.json'), 'utf-8'));
  const varName = (manifest.id as string).replace(/[^a-zA-Z0-9]/g, '_');
  out += `  ${varName},\n`;
}
out += '];\n';

writeFileSync(OUT, out);
console.log(`wrote ${relative(process.cwd(), OUT)} (${PLUGINS.length} plugin(s))`);

// ── Ledger fold mirror (LX-3) ────────────────────────────────────────────────
// Compilable copies of the PURE fold modules, so the export renderer can call
// the exact arithmetic the in-app report blocks use. Purity is enforced here:
// a mirrored module may import only `@book.dev/plugin-sdk` (rewritten to the
// host `@book.dev/sdk`) or a sibling fold module — anything else (React, the
// block components, host APIs) fails the build loudly rather than silently
// dragging the plugin runtime into the export bundle.
mkdirSync(FOLDS_OUT_DIR, {recursive: true});
for (const file of LEDGER_FOLD_MODULES) {
  const srcPath = resolve(ROOT, 'examples/plugins/ledger/src', file);
  const source = readFileSync(srcPath, 'utf-8');
  const siblingNames = LEDGER_FOLD_MODULES.map((f) => f.replace(/\.ts$/, ''));
  for (const m of source.matchAll(/from\s+'([^']+)'/g)) {
    const spec = m[1];
    const ok = spec === '@book.dev/plugin-sdk' || siblingNames.some((s) => spec === `./${s}`);
    if (!ok) throw new Error(`ledger fold mirror: ${file} imports ${spec} — not a pure fold module`);
  }
  const rewritten = source.replace(/from '@book\.dev\/plugin-sdk'/g, 'from \'@book.dev/sdk\'');
  const header =
    '/* eslint-disable */\n' +
    '/**\n' +
    ' * AUTO-GENERATED by scripts/bundlePlugins.ts — do not edit by hand.\n' +
    ` * Mirror of examples/plugins/ledger/src/${file} (the pure report folds),\n` +
    ' * with \'@book.dev/plugin-sdk\' rewritten to \'@book.dev/sdk\'.\n' +
    ' * Re-generate: `pnpm run gen:bundled-plugins`\n' +
    ' */\n';
  writeFileSync(join(FOLDS_OUT_DIR, file), header + rewritten);
}
console.log(`wrote ${relative(process.cwd(), FOLDS_OUT_DIR)} (${LEDGER_FOLD_MODULES.length} fold module(s))`);
