import {chromium} from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({viewport: {width: 1280, height: 800}});
await page.addInitScript(() => localStorage.removeItem('obe-lab-doc'));
await page.goto('http://localhost:3000/editor-lab');
await page.locator('.obe-text').first().waitFor();
const last = page.locator('[data-block-row]').last();
await last.hover();
await last.locator('..').getByRole('button', {name: 'Add a block below'}).last().click();
await page.keyboard.type('/');
await page.locator('.obe-slash').waitFor();
const items = await page.locator('.obe-slash-label').allTextContents();
console.log('total slash items:', items.length);
console.log(items.join(' | '));
const box = await page.locator('.obe-slash').boundingBox();
const inner = await page.locator('.obe-slash').evaluate((el) => ({scroll: el.scrollHeight, client: el.clientHeight, overflowY: getComputedStyle(el).overflowY}));
console.log('menu box h:', box?.height, 'inner:', JSON.stringify(inner));
await page.screenshot({path: '/tmp/slash-menu.png'});
await browser.close();
