import {existsSync, mkdirSync, readFileSync, rmSync, writeFileSync} from 'fs';
import {tmpdir} from 'os';
import * as path from 'path';
import {pathToFileURL} from 'url';
import {expect, test, type Page} from '@playwright/test';
// Import the sdk by SOURCE path: the package ships ESM-only exports, which the
// CJS transpile Playwright runs specs under cannot require; the TS source
// compiles fine either way (same trick the bundle path below uses for ui).
import {spaceToBookFiles, type SpaceSnapshot} from '../../sdk/src/bookFolder';
import {BOOK_RUNTIME_FILE} from '../../sdk/src/bookfile';
import type {StoredPage} from '../../sdk/src/types';

/**
 * The sync/export FOLDER end of the viewer story (owner decision 2026-07-04):
 * a folder written by `spaceToBookFiles({runtime})` (byte-compatible with the
 * server BookMirror) carries ONE `_openbook/viewer.js` and N `.book.html` files
 * that reference it relatively. Opening a page straight from `file://` must
 * hydrate into the interactive locked viewer with zero network; deleting
 * `_openbook/` must leave a perfectly readable static article (the runtime is
 * progressive enhancement over the no-JS fallback, never a dependency).
 *
 * Unlike the hand-written fixtures in viewer-bundle.spec.ts, the folder here is
 * generated by the REAL writer at test time, so the boot script, the island and
 * the relative reference are exercised exactly as shipped.
 */

const BUNDLE = path.resolve(__dirname, '../../ui/src/export/vendor/openbook-viewer.js');

/** A page with a reactive chain (slider → formula), the interactivity probe. */
const page = (over: Partial<StoredPage> & {id: string; name: string}, blocks: unknown[]): StoredPage => ({
  data: {
    editor: 'blocks',
    editorjs: {blocks: []},
    values: [],
    names: [],
    blockdoc: {v: 1, update: '', blocks},
  } as StoredPage['data'],
  hostedDatabaseId: null,
  databaseId: null,
  parentId: null,
  properties: {},
  deletedAt: null,
  createdAt: '2026-07-04T00:00:00.000Z',
  updatedAt: '2026-07-04T00:00:00.000Z',
  ...over,
});

const space: SpaceSnapshot = {
  pages: [
    page({id: 'fx-folder-root', name: 'Folder fixture'}, [
      {id: 'h1', type: 'heading', props: {level: 1}, text: [{t: 'Folder fixture'}]},
      {id: 'p1', type: 'paragraph', text: [{t: 'Exported folder page with a live slider.'}]},
      {id: 'sl', type: 'slider', props: {name: 'months', label: 'Months', value: 100, min: 1, max: 360, step: 1}},
      {id: 'f1', type: 'formula', props: {source: 'months * 2', name: 'doubled'}},
    ]),
  ],
  databases: [],
};

let folderDir: string; // the full export (pages + _openbook/viewer.js)
let strippedDir: string; // the same export with _openbook/ deleted
let pageRelPath: string; // the page file, relative to the folder root

function writeFolder(dir: string, files: Array<{path: string; contents: string}>): void {
  rmSync(dir, {recursive: true, force: true});
  for (const f of files) {
    const abs = path.join(dir, f.path);
    mkdirSync(path.dirname(abs), {recursive: true});
    writeFileSync(abs, f.contents, 'utf8');
  }
}

interface Watch {
  network: string[];
  errors: string[];
}

/** Track http(s) requests + uncaught page exceptions from before navigation. */
function watch(pw: Page): Watch {
  const network: string[] = [];
  const errors: string[] = [];
  pw.on('request', (r) => {
    if (/^https?:/i.test(r.url())) network.push(r.url());
  });
  pw.on('pageerror', (e) => errors.push(String(e)));
  return {network, errors};
}

test.beforeAll(() => {
  if (!existsSync(BUNDLE)) {
    throw new Error(`Viewer bundle missing at ${BUNDLE} — run: pnpm --filter @book.dev/ui run build:viewer`);
  }
  const runtime = readFileSync(BUNDLE, 'utf8');
  const files = spaceToBookFiles(space, {runtime});

  // The advertised folder shape: one .book.html per page + ONE runtime copy.
  const htmlFiles = files.filter((f) => f.path.endsWith('.html'));
  if (htmlFiles.length !== 1) throw new Error(`expected 1 html file, got ${htmlFiles.length}`);
  if (files.filter((f) => f.path === BOOK_RUNTIME_FILE).length !== 1) {
    throw new Error('expected exactly one _openbook/viewer.js');
  }
  pageRelPath = htmlFiles[0].path;

  const base = path.join(tmpdir(), `ob-e2e-bookfolder-${process.pid}`);
  folderDir = path.join(base, 'full');
  strippedDir = path.join(base, 'stripped');
  writeFolder(folderDir, files);
  // The "user deleted _openbook/" (or copied only the book folder) scenario:
  // identical page bytes, no runtime alongside.
  writeFolder(strippedDir, files.filter((f) => f.path !== BOOK_RUNTIME_FILE));
});

test.afterAll(() => {
  rmSync(path.join(tmpdir(), `ob-e2e-bookfolder-${process.pid}`), {recursive: true, force: true});
});

test('a generated .book.html opened from file:// hydrates into the interactive viewer', async ({page: pw}) => {
  const {network, errors} = watch(pw);
  await pw.goto(pathToFileURL(path.join(folderDir, pageRelPath)).href);

  // The boot script found the island and mounted the locked viewer…
  const viewer = pw.locator('.ob-viewer');
  await expect(viewer).toBeVisible();
  // …over the static article (a direct body child — the viewer nests its own
  // article inside the mount host), which stays in the document as the fallback.
  await expect(pw.locator('body > article')).toBeHidden();

  // Real interactivity through the folder-level runtime: drag the slider, the
  // formula recomputes.
  const slider = viewer.locator('input[type="range"][aria-label="months value"]');
  await expect(slider).toHaveValue('100');
  const formulaOut = viewer.locator('.obe-formula-out');
  await expect(formulaOut).toHaveText('200');
  await slider.focus();
  await pw.keyboard.press('ArrowRight');
  await expect(slider).toHaveValue('101');
  await expect(formulaOut).toHaveText('202');

  // Locked: no editing affordances.
  await expect(pw.locator('[contenteditable="true"]')).toHaveCount(0);

  // Fully self-contained: zero network, zero uncaught exceptions.
  expect(network).toEqual([]);
  expect(errors).toEqual([]);
});

test('with _openbook/ deleted the static article still reads fine (no-bundle fallback)', async ({page: pw}) => {
  const {network, errors} = watch(pw);
  await pw.goto(pathToFileURL(path.join(strippedDir, pageRelPath)).href);

  // The boot bails out (no OpenBookViewer global) and leaves the article alone.
  await expect(pw.locator('body > article')).toBeVisible();
  await expect(pw.locator('.ob-page-title')).toContainText('Folder fixture');
  await expect(pw.getByText('Exported folder page with a live slider.')).toBeVisible();
  await expect(pw.locator('.ob-viewer')).toHaveCount(0);

  // The failed relative <script src> is a resource error, not an exception —
  // the page itself must throw nothing and touch no network.
  expect(network).toEqual([]);
  expect(errors).toEqual([]);
});
