import {existsSync} from 'fs';
import * as path from 'path';
import {pathToFileURL} from 'url';
import {expect, test, type Page} from '@playwright/test';

/**
 * Parity harness for the REARCHITECTED HTML export: real `toHtml`/`toHtmlSite`
 * output (generated by packages/ui src/export/__tests__/exportParityFixtures
 * .test.ts — run `pnpm test:e2e:viewer` from the repo root, which chains
 * build:viewer → fixture generation → this suite), opened from file://.
 *
 * Asserts the hydrated export behaves like the in-app locked page: the
 * vendored viewer replaces the static body, the slider→live-code→chart chain
 * recomputes live, tabs switch, accordion sections collapse, the image
 * renders, hostile text stays inert — with zero network requests, zero
 * console errors, and the source island byte-unchanged by interaction. Plus
 * the two fallback contracts: `__OB_NO_HYDRATE` keeps the static projection
 * (the PDF pipeline's mode), and JS disabled leaves a readable document.
 */

const GENERATED = path.join(__dirname, 'generated');
const fileUrl = (name: string): string => pathToFileURL(path.join(GENERATED, name)).href;

function watch(page: Page): {network: string[]; errors: string[]} {
  const network: string[] = [];
  const errors: string[] = [];
  page.on('request', (r) => {
    if (/^https?:/i.test(r.url())) network.push(r.url());
  });
  page.on('console', (m) => {
    if (m.type() === 'error') errors.push(m.text());
  });
  page.on('pageerror', (e) => errors.push(String(e)));
  return {network, errors};
}

test.beforeAll(() => {
  for (const f of ['export-page.html', 'export-site.html']) {
    if (!existsSync(path.join(GENERATED, f))) {
      throw new Error(
        `Missing generated fixture ${f} — run: pnpm --filter @book.dev/ui exec vitest run src/export/__tests__/exportParityFixtures.test.ts`,
      );
    }
  }
});

test.describe('page export, hydrated', () => {
  test('viewer replaces the static body and matches in-app locked behavior', async ({page}) => {
    const {network, errors} = watch(page);
    await page.goto(fileUrl('export-page.html'));

    // Hydration: the viewer host replaces the static <main>.
    const viewer = page.locator('.ob-viewer');
    await expect(viewer).toBeVisible();
    await expect(page.locator('main')).toHaveCount(0);
    const islandBefore = await page.locator('script[type="application/openbook+json"]').textContent();

    // Content parity: title, rich text, table, image, to-do.
    await expect(page.locator('.ob-viewer-title')).toContainText('Parity fixture');
    await expect(viewer.locator('[role="heading"][aria-level="1"]').first()).toContainText('Parity fixture');
    await expect(viewer.getByText('Interactive export. Drag')).toBeVisible();
    await expect(viewer.getByText('Ada')).toBeVisible(); // table cell
    await expect(viewer.getByText('ship the viewer')).toBeVisible(); // to-do
    const img = viewer.locator('img[alt="grey square"]');
    await expect(img).toBeVisible();
    expect(await img.evaluate((el: HTMLImageElement) => el.naturalWidth)).toBe(8);

    // Hostile content renders as inert text (and executed nothing).
    await expect(viewer.getByText('Hostile:')).toBeVisible();

    // Reactive chain: slider → live code → chart + formula + light + progress.
    const slider = viewer.locator('input[type="range"][aria-label="months value"]');
    await expect(slider).toHaveValue('120');
    const formulaOut = viewer.locator('.obe-formula-out');
    await expect(formulaOut).toHaveText('240');
    const status = viewer.locator('.obe-kit-status');
    await expect(status).toHaveAttribute('data-status', 'ok');
    const chartSvg = viewer.locator('figure[data-chart-kind="line"] .obe-chart-svg');
    await expect(chartSvg).toBeVisible();
    const chartBefore = await chartSvg.innerHTML();

    await slider.focus();
    await page.keyboard.press('ArrowRight'); // 120 → 121
    await expect(slider).toHaveValue('121');
    await expect(formulaOut).toHaveText('242');
    await expect(status).toHaveAttribute('data-status', 'bad'); // months <= 120 flipped
    expect(await chartSvg.innerHTML()).not.toBe(chartBefore); // chart redrew

    // Tabs switch; accordion sections collapse and re-expand.
    await expect(viewer.getByText('first tab body')).toBeVisible();
    await viewer.getByRole('tab', {name: 'Second'}).click();
    await expect(viewer.getByText('second tab body')).toBeVisible();
    const bodyA = viewer.getByText('Accordion body A');
    await expect(bodyA).toBeVisible();
    await viewer.locator('.obe-acc-toggle').first().click();
    await expect(bodyA).toBeHidden();
    await viewer.locator('.obe-acc-toggle').first().click();
    await expect(bodyA).toBeVisible();

    // Locked semantics: no editing affordances, nothing persisted anywhere.
    // Including ghost placeholder text on locked chart chrome: the fixture has
    // a titled chart with an empty description AND an untitled chart — neither
    // may surface its edit placeholder on the locked page (design review).
    await expect(page.getByText('Add a description…')).toHaveCount(0);
    await expect(page.getByText('Chart title')).toHaveCount(0);
    await expect(page.locator('[contenteditable="true"]')).toHaveCount(0);
    await expect(page.locator('input.obe-kit-inline')).toHaveCount(0);
    for (const chrome of ['.obe-gutter', '.obe-kit-gear', '.obe-cnt-add', '.obe-group-btn']) {
      await expect(page.locator(`${chrome}:visible`), `${chrome} must be hidden`).toHaveCount(0);
    }
    expect(await page.locator('script[type="application/openbook+json"]').textContent()).toBe(islandBefore);

    expect(network).toEqual([]);
    expect(errors).toEqual([]);
  });

  test('__OB_NO_HYDRATE keeps the static projection (the PDF pipeline contract)', async ({page}) => {
    const {network, errors} = watch(page);
    await page.addInitScript(() => {
      (window as Window & {__OB_NO_HYDRATE?: boolean}).__OB_NO_HYDRATE = true;
    });
    await page.goto(fileUrl('export-page.html'));

    // The static body stays; the viewer never mounts.
    await expect(page.locator('main')).toBeVisible();
    await expect(page.locator('.ob-viewer')).toHaveCount(0);
    // The projection is fully computed at export time — what toPdf snapshots.
    await expect(page.locator('main .expr', {hasText: 'doubled'}).locator('[data-val]')).toHaveText('240');
    await expect(page.locator('main .kitlight')).toHaveAttribute('data-status', 'ok');
    await expect(page.locator('main figure.chart svg').first()).toBeVisible();
    await expect(page.locator('main img[alt="grey square"]')).toBeVisible();

    expect(network).toEqual([]);
    expect(errors).toEqual([]);
  });
});

test.describe('page export, JS disabled', () => {
  test.use({javaScriptEnabled: false});

  test('the static body stays readable without JS', async ({page}) => {
    await page.goto(fileUrl('export-page.html'));
    await expect(page.locator('main h1.doc-title')).toContainText('Parity fixture');
    await expect(page.getByText('Interactive export. Drag')).toBeVisible();
    await expect(page.locator('main figure.chart svg').first()).toBeVisible(); // charts baked at export
    await expect(page.locator('main img[alt="grey square"]')).toBeVisible();
    await expect(page.locator('main .expr', {hasText: 'doubled'}).locator('[data-val]')).toHaveText('240');
  });
});

test.describe('site export, hydrated', () => {
  test('the viewer #page= hash nav replaces the legacy router', async ({page}) => {
    const {network, errors} = watch(page);
    await page.goto(fileUrl('export-site.html'));

    // Hydrated: viewer nav, no legacy back-button header.
    const viewer = page.locator('.ob-viewer');
    await expect(viewer).toBeVisible();
    await expect(page.locator('#ob-back')).toHaveCount(0);
    await expect(page.locator('[data-viewer-page="fx-root"]')).toBeVisible();
    const islandBefore = await page.locator('script[type="application/openbook+json"]').textContent();

    // Hash navigation between bundle pages.
    const nav = page.locator('.ob-viewer-nav');
    await expect(nav.locator('a')).toHaveCount(2);
    await nav.getByText('Second page').click();
    await expect(page.locator('[data-viewer-page="fx-two"]')).toBeVisible();
    await expect(page.getByText('Content of the second page.')).toBeVisible();
    expect(new URL(page.url()).hash).toBe('#page=fx-two');
    await page.goBack();
    await expect(page.locator('[data-viewer-page="fx-root"]')).toBeVisible();

    // Widgets stay live on the hydrated site export too.
    const slider = page.locator('input[type="range"][aria-label="months value"]');
    await slider.focus();
    await page.keyboard.press('ArrowRight');
    await expect(page.locator('.obe-formula-out')).toHaveText('242');

    expect(await page.locator('script[type="application/openbook+json"]').textContent()).toBe(islandBefore);
    expect(network).toEqual([]);
    expect(errors).toEqual([]);
  });
});
