import Head from 'next/head'
import { Inter } from 'next/font/google'
import { DefaultLayout } from '@hyper-hq/hyper-ui/dist/layouts/DefaultLayout'
import {Container} from "@mui/joy";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const greetMsg = 'hello world'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Container>
          <form
            className="row"
            onSubmit={(e) => {
              e.preventDefault();
              greet();
            }}
          >
            <input
              id="greet-input"
              onChange={(e) => setName(e.currentTarget.value)}
              placeholder="Enter a name..."
            />
            <button type="submit">Greet</button>
          </form>

          <p>{greetMsg}</p>
        </Container>
      </DefaultLayout>
    </>
  )
}
