import Head from 'next/head'
import {DefaultLayout, PageDocument} from '@hyper-hq/hyper-ui'
import {Container} from "@mui/joy";
import {useState} from "react";

export default function Home() {
  const [greetMsg, setGreetMsg] = useState("");
  const [name, setName] = useState("");

  async function greet() {
    // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
    setGreetMsg(`greet ${name}`);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <DefaultLayout>
        <Container>
          <PageDocument/>
        </Container>
      </DefaultLayout>
    </>
  )
}
