import {describe, expect, it} from 'vitest';
import type {StoredPage} from '@book.dev/sdk';
import generatedSnapshot from './fixtures/form-page.snapshot.json';
import {
  constantTimeSubmissionKeyEqual,
  findFormInPage,
  validateDatabaseFormSubmissionRequest,
  validateFormSubmissionRequest,
} from './formAccess';

const pageWith = (blocks: unknown[]): Pick<StoredPage, 'data'> => ({
  data: {editorjs: {blocks: []}, values: [], names: [], blockdoc: {v: 1, update: '', blocks}},
});

describe('constantTimeSubmissionKeyEqual', () => {
  it('accepts identical keys and rejects wrong content or length', () => {
    expect(constantTimeSubmissionKeyEqual('same-key', 'same-key')).toBe(true);
    expect(constantTimeSubmissionKeyEqual('same-kex', 'same-key')).toBe(false);
    expect(constantTimeSubmissionKeyEqual('', 'same-key')).toBe(false);
    expect(constantTimeSubmissionKeyEqual('same-key-with-a-suffix', 'same-key')).toBe(false);
  });
});

describe('findFormInPage', () => {
  const props = {
    formId: 'contact',
    submissionKey: 'capability',
    enabled: true,
    databaseId: 'database-1',
    schema: {fields: []},
  };

  it('finds a nested form in blockdoc', () => {
    const page = pageWith([{type: 'columns', children: [{type: 'column', children: [{type: 'form', props}]}]}]);
    expect(findFormInPage(page, 'contact')).toEqual(props);
  });

  it('consults blockdoc rather than the editorjs export projection', () => {
    const page = pageWith([{type: 'form', props}]);
    page.data.editorjs = {blocks: [{type: 'form', data: {props}}]};
    expect(findFormInPage(page, 'contact')).toEqual(props);
    expect(findFormInPage({data: {editorjs: {blocks: [{type: 'form', props}]}, values: [], names: []}}, 'contact')).toBeNull();
  });

  it('finds nested and top-level forms in an actual UI-serialized page snapshot', () => {
    // Generated by projectBlockPageSnapshot(createSeededDoc(...)) from @book.dev/ui.
    // Its editorjs entries are the export shape; blockdoc is the encodeSnapshot source.
    const page = {data: generatedSnapshot as StoredPage['data']};
    expect(findFormInPage(page, 'nested-contact')).toEqual({
      formId: 'nested-contact',
      submissionKey: 'nested-capability',
      enabled: true,
      databaseId: 'nested-database',
      schema: {fields: [{id: 'email', type: 'email'}], maxSubmissions: 25},
    });
    expect(findFormInPage(page, 'top-contact')).toEqual({
      formId: 'top-contact',
      submissionKey: 'top-capability',
      enabled: true,
      databaseId: 'top-database',
      schema: {fields: [{id: 'name', type: 'text'}]},
    });
  });

  it('fails closed on malformed or duplicate matching definitions', () => {
    expect(findFormInPage(pageWith([{type: 'form', props: {...props, submissionKey: ''}}]), 'contact')).toBeNull();
    expect(findFormInPage(pageWith([{type: 'form', props}, {type: 'form', props}]), 'contact')).toBeNull();
  });
});

describe('validateFormSubmissionRequest', () => {
  it('applies the idempotency byte cap after trimming', () => {
    expect(validateFormSubmissionRequest({key: 'key', values: {}, idempotencyKey: `${' '.repeat(250)}x`}).idempotencyKey).toBe('x');
    expect(() => validateFormSubmissionRequest({key: 'key', values: {}, idempotencyKey: 'x'.repeat(201)})).toThrow();
  });
});

describe('validateDatabaseFormSubmissionRequest', () => {
  const request = (idempotencyKey: string) => ({capability: 'capability', fields: {}, idempotencyKey});

  it('accepts v4 UUID and 128-bit-shaped base64url replay keys', () => {
    const uuid = '550e8400-e29b-41d4-a716-446655440000';
    expect(validateDatabaseFormSubmissionRequest(request(uuid)).idempotencyKey).toBe(uuid);
    expect(validateDatabaseFormSubmissionRequest(request('Abcdefghijklmnopqrstuv')).idempotencyKey)
      .toBe('Abcdefghijklmnopqrstuv');
  });

  it('rejects low-entropy and malformed replay-key shapes', () => {
    for (const key of [
      'predictable',
      'Abcdefghijklmnopqrstu',
      'Abcdefghijklmnopqrstu=',
      'x'.repeat(201),
    ]) {
      expect(() => validateDatabaseFormSubmissionRequest(request(key))).toThrow();
    }
  });
});
